### ISSUE TITLE
Aanvulling op de webhook documentatie

### ISSUE THREAD

**Issue by janwijbrand** [Koppeltaal/Koppeltaal-Documentation#38]
Zie https://vzvz.gitbook.io/koppeltaal-1-3-architectuur/technologie-architectuur#bericht-notificatie en https://github.com/orgs/Koppeltaal/teams/implementators/discussions/31

Ik wil suggereren om de webhook in iets meer detail uit te schrijven, te meer daar deze voor zover ik kan zien niet in DSTU1 gedefinieerd/beschreven is. Ik denk aan details als:

* Voorbeelden van de payload
* Dat de webhook een POST request doet
* Dat de webhook headers meestuurt en welke dat zijn
* Dat het belangrijk is in elk geval een custom header te configureren met een secret value (secret wordt dan dus gedeeld tussen KT domain en het platform).

**Comment by bmstibbe** [comment]
@janwijbrand . Ik ga de documentatie op de volgende manier aanpassen.

Koppeltaal biedt een functie aan om notificaties te versturen als er een nieuw bericht beschikbaar is voor een applicatie. Deze notificatie is geïmplementeerd middels REST WebHooks. Om een notificatie te kunnen ontvangen zijn de volgende configuratie acties nodig:

- Een WebHook URL definiëren, tijdens de registratie en configuratie van een applicatie in het domein, die Koppeltaal kan aanroepen.
- De lokale implementatie achter de WebHook URL is nodig om notificaties te kunnen interpreteren. Koppeltaal zal een event genereren, ter informatie dat er ‘nieuwe’ berichten beschikbaar zijn. Het event, een notificatie bericht, bevat geen payload.
- De betreffende applicatie wordt maximaal 5 keer gesignaleerd. De applicatie kan daarna het bericht lezen zoals al beschreven in paragraaf Bericht ophalen. 
- Het notificatie bericht maakt gebruik van de volgende HTTP headers:
  • `Category ` dat de domein headers bevat. Bijvoorbeeld: `Category: http://ggz.koppeltaal.nl/fhir/Koppeltaal/Domain#[Domain]; scheme=""; label="http://hl7.org/fhir/tag/security[Domain]"`. Dit is vanaf Koppeltaal 1.3.8 ingevoerd.
  • `KoppeltaalMessageIdentifier`. Hiermee wordt een correlatie id (MessageHeader.identifier) meegestuurd van het bericht dat beschikbaar is voor de applicatie. Vanaf Koppeltaal 1.3.8 ingevoerd.
  • `Content-Type` en `Accept`. Vanaf Koppeltaal 1.3.8 ingevoerd. Worden altijd gevuld met "application/json". Gebaseerd op RFC-7231.
  • `X-Koppeltaal-Secret`. Is een voorbeeld van custom header, die kunnen worden geconfigureerd per 'application instance'.
  • `Content-Length` moet 0 zijn omdat er geen payload is. Deze parameter wordt runtime bepaald in de WebRquest klasse.

**Comment by janwijbrand** [comment]
Dit is afgehandeld denk ik te zien. Dus ik sluit het ticket.

**Comment by eddy147** [comment]
Hallo,

ik stop per 1 aug mijn werkzaamheden voor Koppeltaal.
Graag mijn opvolger ***@***.*** opnemen in de mail list
(en mij eruit halen).

Alvast bedankt, succes met Koppeltaal en wellicht tot ziens!

Eddy de Boer
